server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cristian-David-Github/parcialBackend.git
          default-label: main
          force-pull: true
          search-paths: configData